import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card'
import { Button } from '../../components/ui/button'
import { Input } from '../../components/ui/input'
import { Label } from '../../components/ui/label'
import { Select } from '../../components/ui/select'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../../components/ui/tabs'
import { Receipt, FileText, Upload, Eye } from 'lucide-react'
import { MOCK_SHOPS } from '../../data/mockData'

const DistributorClaims = () => {
  const [activeTab, setActiveTab] = useState('expiry-damage')
  const [expiryDamageData, setExpiryDamageData] = useState({
    images: [null, null, null], // 3 images
    batchDate: '',
  })
  const [extraMarginData, setExtraMarginData] = useState({
    shopId: '',
  })
  const [creditNote, setCreditNote] = useState(null)

  const handleImageUpload = (index, file) => {
    const newImages = [...expiryDamageData.images]
    newImages[index] = file
    setExpiryDamageData({ ...expiryDamageData, images: newImages })
  }

  const handleSubmitExpiryDamage = () => {
    if (!expiryDamageData.batchDate || expiryDamageData.images.filter(img => img).length === 0) {
      alert('Please upload at least one image and provide batch date')
      return
    }
    alert('Expiry/Damage Claim submitted successfully! Awaiting approval.')
    setExpiryDamageData({ images: [null, null, null], batchDate: '' })
  }

  const handleSubmitExtraMargin = () => {
    if (!extraMarginData.shopId) {
      alert('Please select Shop Name')
      return
    }
    
    // Check if margin is more than 25% (mock calculation)
    const mockMargin = Math.random() * 30 + 20 // Random margin between 20-50%
    const shouldAutoGenerate = mockMargin > 25
    
    if (shouldAutoGenerate) {
      setCreditNote({
        id: 'CN-' + Date.now(),
        shopId: extraMarginData.shopId,
        shopName: MOCK_SHOPS.find(s => s.id === parseInt(extraMarginData.shopId))?.name,
        margin: mockMargin.toFixed(2),
        amount: 7500, // Mock amount
        date: new Date().toISOString(),
        autoGenerated: true,
      })
      alert(`Extra Margin Claim submitted successfully! Margin: ${mockMargin.toFixed(2)}% (Auto-generated as margin > 25%)`)
    } else {
      setCreditNote({
        id: 'CN-' + Date.now(),
        shopId: extraMarginData.shopId,
        shopName: MOCK_SHOPS.find(s => s.id === parseInt(extraMarginData.shopId))?.name,
        margin: mockMargin.toFixed(2),
        amount: 5000,
        date: new Date().toISOString(),
        autoGenerated: false,
      })
      alert('Extra Margin Claim submitted successfully! Credit Note generated.')
    }
  }

  const handleViewCreditNote = () => {
    if (creditNote) {
      alert(`Credit Note: ${creditNote.id}\nShop: ${creditNote.shopName}\nMargin: ${creditNote.margin}%\nAmount: ₹${creditNote.amount.toLocaleString('en-IN')}\n${creditNote.autoGenerated ? '(Auto-generated - Margin > 25%)' : ''}`)
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-gray-900">Claims Management</h1>
        <p className="text-gray-600 mt-2">Manage expiry, damage, and extra margin claims</p>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList>
          <TabsTrigger value="expiry-damage">Expiry/Damage Claim</TabsTrigger>
          <TabsTrigger value="extra-margin">Extra Margin Claim</TabsTrigger>
        </TabsList>

        {/* Expiry/Damage Claim */}
        <TabsContent value="expiry-damage">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Receipt className="h-5 w-5 text-[#433228]" />
                Expiry/Damage Claim
              </CardTitle>
              <CardDescription>Submit claims for expired or damaged products</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                <div className="space-y-2">
                  <Label htmlFor="batch-date">Batch Date *</Label>
                  <Input
                    id="batch-date"
                    type="date"
                    value={expiryDamageData.batchDate}
                    onChange={(e) => setExpiryDamageData({ ...expiryDamageData, batchDate: e.target.value })}
                  />
                </div>

                <div className="space-y-4">
                  <Label>Upload Images * (Upload at least 1 image)</Label>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    {[0, 1, 2].map((index) => (
                      <div key={index} className="space-y-2">
                        <Label htmlFor={`image-${index}`}>Image {index + 1}</Label>
                        <div className="border-2 border-dashed border-gray-300 rounded-lg p-4">
                          {expiryDamageData.images[index] ? (
                            <div className="space-y-2">
                              <img
                                src={URL.createObjectURL(expiryDamageData.images[index])}
                                alt={`Upload ${index + 1}`}
                                className="w-full h-32 object-cover rounded"
                              />
                              <Button
                                size="sm"
                                variant="outline"
                                onClick={() => {
                                  const newImages = [...expiryDamageData.images]
                                  newImages[index] = null
                                  setExpiryDamageData({ ...expiryDamageData, images: newImages })
                                }}
                                className="w-full"
                              >
                                Remove
                              </Button>
                            </div>
                          ) : (
                            <label
                              htmlFor={`image-${index}`}
                              className="flex flex-col items-center justify-center cursor-pointer"
                            >
                              <Upload className="h-8 w-8 text-gray-400 mb-2" />
                              <span className="text-sm text-gray-600">Click to upload</span>
                              <Input
                                id={`image-${index}`}
                                type="file"
                                accept="image/*"
                                className="hidden"
                                onChange={(e) => {
                                  if (e.target.files[0]) {
                                    handleImageUpload(index, e.target.files[0])
                                  }
                                }}
                              />
                            </label>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                <Button
                  onClick={handleSubmitExpiryDamage}
                  className="bg-[#433228] hover:bg-[#5a4238] text-white"
                >
                  Submit for Approval
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Extra Margin Claim */}
        <TabsContent value="extra-margin">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-[#433228]" />
                Extra Margin Claim
              </CardTitle>
              <CardDescription>Submit extra margin claims. Shops with more than 25% margin will have claims automatically generated.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                <div className="space-y-2">
                  <Label htmlFor="shop-claim">Select Shop Name *</Label>
                  <Select
                    id="shop-claim"
                    value={extraMarginData.shopId}
                    onChange={(e) => setExtraMarginData({ shopId: e.target.value })}
                  >
                    <option value="">Select Shop</option>
                    {MOCK_SHOPS.map((shop) => (
                      <option key={shop.id} value={shop.id}>
                        {shop.name} - {shop.address}
                      </option>
                    ))}
                  </Select>
                </div>

                <Button
                  onClick={handleSubmitExtraMargin}
                  className="bg-[#433228] hover:bg-[#5a4238] text-white"
                >
                  Submit Extra Margin Claim
                </Button>

                {creditNote && (
                  <Card className={`${creditNote.autoGenerated ? 'bg-green-50 border-green-200' : 'bg-blue-50 border-blue-200'}`}>
                    <CardHeader>
                      <CardTitle className={creditNote.autoGenerated ? 'text-green-800' : 'text-blue-800'}>
                        Credit Note Generated {creditNote.autoGenerated && '(Auto-generated)'}
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-2">
                        <div className="flex justify-between">
                          <span className="font-medium">Credit Note ID:</span>
                          <span>{creditNote.id}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="font-medium">Shop:</span>
                          <span>{creditNote.shopName}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="font-medium">Margin:</span>
                          <span>{creditNote.margin}%</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="font-medium">Amount:</span>
                          <span>₹{creditNote.amount.toLocaleString('en-IN')}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="font-medium">Date:</span>
                          <span>{new Date(creditNote.date).toLocaleDateString()}</span>
                        </div>
                        <Button
                          onClick={handleViewCreditNote}
                          className={`mt-4 w-full ${creditNote.autoGenerated ? 'bg-green-600 hover:bg-green-700' : 'bg-blue-600 hover:bg-blue-700'} text-white`}
                        >
                          <Eye className="h-4 w-4 mr-2" />
                          View Credit Note
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                )}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}

export default DistributorClaims
